### ISSUE TITLE
Installing from brew and boot-simulators command is unknown

### ISSUE THREAD

**Issue by atineoSE** [plu/pxctest#15]
After installing from brew according to the info in the README.md, the `boot-simulators` command is not available.

```
$ pxctest boot-simulators
Unknown command: boot-simulators
```

```
$ pxctest
Usage:

    $ pxctest

Commands:

    + run-tests
    + version
```

```
$ pxctest version
pxctest 0.2.9 (7bb7c7e)
```

**Comment by plu** [comment]
I forgot to update the Homebrew formula.

Can you please try `brew update && brew upgrade pxctest`

That should update to `0.3.0`, which supports `boot-simulators`

**Comment by atineoSE** [comment]
That worked! Thanks
