### ISSUE TITLE
Use pxctest to create simulators

### ISSUE THREAD

**Issue by davetobin** [plu/pxctest#17]
Is it possible to create simulators in a specific location, e.g. --deviceset /tmp/test-simulators, without booting them in a headless state using boot-simulators?

I would like to be able to create simulators, then "run-tests" and delete the simulators once testing has completed.

Currently, I can use boot-simulators but am forced to run in a headless state using this.

**Comment by plu** [comment]
I recommend looking into fbsimctl for your use case.

**Comment by plu** [comment]
Or even xcrun simctl.

**Comment by davetobin** [comment]
@plu Thanks, I just liked the simplicity of specifying the deviceset in your boot-simulators command so I wanted to check if it was possible for run-tests or a different command to create them in the same way.

**Comment by plu** [comment]
By the way: `run-tests` will create and boot them, if necessary, it also supports `--deviceset`

**Comment by davetobin** [comment]
Great, it wasn't working for me so I thought it wasn't supported to work in the same way but a reboot sorted it for me. I'll close this. Cheers.
