### ISSUE TITLE
Output to CircleCi is ......FF..........

### ISSUE THREAD

**Issue by Kmohamed** [plu/pxctest#24]
I use --output command to output `pxctest` result to circle CI 
but I want the JUnit file to be passed to Circle CI

**Comment by Kmohamed** [comment]
this is my command:
pxctest run-tests --destination 'name=iPhone 5,os=iOS 9.3' --destination 'name=iPhone 5,os=iOS 10.1' --testrun build/Products/iphonesimulator10.1-i386.xctestrun --output $CIRCLE_TEST_REPORTS/xcode/uitest_results.xml

**Comment by plu** [comment]
I've never used Circle CI myself. But I found some documentation on how to collect test metadata here:

http://circleci.com/docs/1.0/test-metadata/

Maybe that will help you. `pxctest` will generate some JUnit report(s) inside the `output` directory. Just look for them there and you will find them.

**Comment by plu** [comment]
You could also run this command locally and then see how the files look like that were generated when using `--output`. It does create a directory structure with a couple of files in it. This is why `--output $CIRCLE_TEST_REPORTS/xcode/uitest_results.xml` does not work for you as expected.

**Comment by Kmohamed** [comment]
Thanks 👍

**Comment by plu** [comment]
You're welcome 👍 .
