### ISSUE TITLE
`/tmp/test-simulators` is not a `path`

### ISSUE THREAD

**Issue by Akulavenkatesh** [plu/pxctest#27]
When I try to run this command in my terminal:
pxctest boot-simulators --deviceset /tmp/test-simulators --destination 'name=iPhone 6’ --destination 'name=iPhone 7’

Its says `/tmp/test-simulators` is not a `path`.

My folder structure: Desktop > Github > pxctest > tmp > test-simulators

<img width="1177" alt="screen shot 2017-03-11 at 9 32 21 pm" src="https://cloud.githubusercontent.com/assets/1756744/23829251/422a857c-06a2-11e7-8668-b30534f08815.png">

**Comment by plu** [comment]
Try `mkdir /tmp/test-simulators` first.

**Comment by plu** [comment]
Also you're passing `/test-simulators` - which your user most likely cannot write.

**Comment by ollieatkinson** [comment]
If your folder structure is `My folder structure: Desktop > Github > pxctest > tmp > test-simulators` and you are running the tool in the `tmp` directory as your screenshot suggests then you can also omit the first `/` or replace it with `./` to suggest its a path from the current directory. 

```
pxctest boot-simulators --deviceset ./test-simulators --destination 'name=iPhone 6’ --destination 'name=iPhone 7’
```

**Comment by Akulavenkatesh** [comment]
Thanks @plu @ollieatkinson and sorry for the late reply - I was traveling. I will try the above and reply back asap

**Comment by Akulavenkatesh** [comment]
I ran the command as mentioned by @ollieatkinson and the error went off. 
`pxctest boot-simulators --deviceset ./test-simulators --destination 'name=iPhone 6,os=iOS 10.2'`

In the 'test-simulators' folder I see a folder 'D94D4D45-986C-48F9-AC36-B859F3119213' getting created but the simulators never booted up (attached ss for your reference)

<img width="1440" alt="screen shot 2017-03-14 at 6 36 04 pm" src="https://cloud.githubusercontent.com/assets/1756744/23929907/3489b65e-08e6-11e7-8c8e-47e72528deac.png">

**Comment by plu** [comment]
They boot in the background, you will not see any window - that's the whole idea of `boot-simulators` :). However you can list them, try this command: `xcrun simctl --set $PWD/test-simulators list`

**Comment by Akulavenkatesh** [comment]
I run my appium test cases with simulators. In this case can you please let me know how to integrate pxctest with appium

**Comment by plu** [comment]
I never used Appium, so I can't help here, sorry!

**Comment by Akulavenkatesh** [comment]
Thanks @plu @ollieatkinson :) . I'll try to figure that out, closing this.
