### ISSUE TITLE
Test Scheme Pre-Action not being executed

### ISSUE THREAD

**Issue by davetobin** [plu/pxctest#29]
I've noticed that Pre-action scripts of test schemes do not get executed. It works when running with Xcode. Should this work with pxctest? Thanks in advance.

This is where I have the pre-action script:

![image](https://cloud.githubusercontent.com/assets/6198085/24253613/ae4b1c3c-0fd8-11e7-91ff-1193800caf35.png)

**Comment by plu** [comment]
I am sorry to tell you that this is currently not supported.

**Comment by davetobin** [comment]
No problem. Just wanted to check. Do you know if it would be easy to implement? Also, is it something you would welcome in pxctest if it was implemented?

**Comment by plu** [comment]
Does the script get executed when you use `xcodebuild ... build-for-testing` and `xcodebuild ... test-without-building`?

**Comment by davetobin** [comment]
I haven't gotten around to testing this yet. I'm going to close for now and if I get around to it I will reopen. Thanks.
