### ISSUE TITLE
'pxctest run-test ' fails to launch tests

### ISSUE THREAD

**Issue by SamuelZhaoY** [plu/pxctest#33]
I have followed exactly what is given in the RM file. How ever when I execute pxctest run-test, I was always given the error below:

**Error Domain=com.facebook.XCTestBootstrap Code=0**

it opens the application and immediately minimising the application and after while raises the above issue.

**Comment by plu** [comment]
Can you check the Simulators log files? You can find them here: `~/Library/Logs/CoreSimulator`

It might also help to check `Console.app` for Crashes (`User Reports`).

**Comment by SamuelZhaoY** [comment]
I have created a new simulator and recorded the system logs below. Please check it:
[system.log.zip](https://github.com/plu/pxctest/files/888924/system.log.zip)

**Comment by plu** [comment]
I can show you the error message if you like, but maybe it would make sense if you had a look into the log yourself?

**Comment by plu** [comment]
```
The bundle “AlipayWalletUITests” couldn’t be loaded because it doesn’t contain a version
for the current architecture. Try installing a universal version of the bundle.
(dlopen_preflight(/Users/Gangdooz/...): no suitable image found.
Did find: /Users/Gangdooz/...: mach-o, but wrong architecture)
```

There are 32 Bit and 64 Bit Simulators, for example iPhone 5 vs iPhone 5s. You must build the test target for the correct architecture of the Simulator you want to run the tests on.

**Comment by SamuelZhaoY** [comment]
Thanks, I have also just found out the errors, working on it.

**Comment by SamuelZhaoY** [comment]
Thanks for your help,  initially the error was caused by:

 **-destination 'platform=iOS Simulator,name=iPhone 5,OS=9.0'  **   

Since I am using 5s simulator, hence as soon as I changed into:

 **-destination 'platform=iOS Simulator,name=iPhone 5s,OS=9.0'  **   

The problem will be solved.

**Comment by plu** [comment]
Happy it works for you now!

**Comment by SamuelZhaoY** [comment]
So far everything is working well. But there is one more thing I may want to ask out of curiosity, since the project here fully supports parallel testing on iOS simulators, why not support on real devices as well?  😄

**Comment by plu** [comment]
Pull requests welcome :).
