### ISSUE TITLE
Unable to install - error

### ISSUE THREAD

**Issue by cliren** [plu/pxctest#5]
Getting the following error, please advise!

`brew tap plu/pxctest && brew install pxctest`

`
/private/tmp/pxctest20161207-1608-wajtb0/Dependencies/Commander /private/tmp/pxctest20161207-1608-wajtb0
Cloning https://github.com/kylef/Spectre
git: The build tool has reset ENV; --env=std required.
swift-package: error: No version tag found in (/private/tmp/pxctest20161207-1608-wajtb0/Dependencies/Commander/Packages/Spectre) package. Add a version tag with "git tag" command. Example: "git tag 0.1.0"

`

**Comment by plu** [comment]
It seems that it is complaining about a missing tag in https://github.com/kylef/Spectre, but that does have tags in the repo.

Can you please try again with `brew install pxctest --debug` and post the full output here?

It would also be interesting which version of Mac OS you're using exactly, and which version of Xcode (`xcodebuild -version`)?

**Comment by cliren** [comment]
Xcode 8.1
Build version 8B62

`
brew install pxctest --debug
/usr/local/Library/brew.rb (Formulary::FormulaLoader): loading /usr/local/Library/Taps/plu/homebrew-pxctest/pxctest.rb
==> Installing pxctest from plu/pxctest
/usr/local/Library/Homebrew/build.rb (Formulary::FromPathLoader): loading /usr/local/Library/Taps/plu/homebrew-pxctest/pxctest.rb
/usr/local/Library/Homebrew/build.rb (Formulary::FormulaLoader): loading /usr/local/Library/Taps/homebrew/homebrew-core/Formula/git.rb
==> Cloning https://github.com/plu/pxctest.git
Updating /Library/Caches/Homebrew/pxctest--git
==> Checking out tag 0.2.7
==> ./scripts/build.sh /usr/local/Cellar/pxctest/0.2.7/libexec
Last 15 lines from /Users/<user>/Library/Logs/Homebrew/pxctest/01.build.sh:
2016-12-08 08:13:27 -0800

./scripts/build.sh
/usr/local/Cellar/pxctest/0.2.7/libexec

/private/tmp/pxctest20161208-2648-1fx5qte/Dependencies/Commander /private/tmp/pxctest20161208-2648-1fx5qte
Cloning https://github.com/kylef/Spectre
git: The build tool has reset ENV; --env=std required.
swift-package: error: No version tag found in (/private/tmp/pxctest20161208-2648-1fx5qte/Dependencies/Commander/Packages/Spectre) package. Add a version tag with "git tag" command. Example: "git tag 0.1.0"
/usr/local/Library/Homebrew/debrew.rb:11:in `raise'
BuildError: Failed executing: ./scripts/build.sh /usr/local/Cellar/pxctest/0.2.7/libexec
1. raise
2. ignore
3. backtrace
4. irb
5. shell
`

**Comment by plu** [comment]
Okay, Xcode 8.1 should work. Which version of Homebrew are you using?

I have here Xcode 8.1 as well and Homebrew 1.1.0:

```
Homebrew 1.1.0
Homebrew/homebrew-core (git revision a999; last commit 2016-12-04)
```

This combination seems to work fine. Also on Travis it can install the tap succesfully:

https://travis-ci.org/plu/homebrew-pxctest/builds/181863231

**Comment by cliren** [comment]
upgrading brew seems to work. Thanks!

**Comment by plu** [comment]
Great, happy to hear that it is working for you!
