### ISSUE TITLE
can't find .xctestrun file

### ISSUE THREAD

**Issue by okan-erdogan** [plu/pxctest#7]
Hi 
After running build command I get
_/var/folders/sc/b19_wblj5bv5wyph7hw5y5b95jc55b/T/SchemeScriptAction-Qjp2Sy: line 2: $: command not found
** TEST BUILD SUCCEEDED **_
And i cant see that build/Products file generated.Is there something i missed.
And I should inform you also i get the message below while installing it.
_

> You are using OS X 10.12.
> We do not provide support for this pre-release version.
> You may encounter build failures or other breakages

_.

**Comment by plu** [comment]
Can you please post your full `xcodebuild` command that you're using?

**Comment by plu** [comment]
> And I should inform you also i get the message below while installing it.

This is coming from Homebrew.

**Comment by okan-erdogan** [comment]
I fix command not found issue but still can not find .xctestrun file.

>  /var/folders/sc/b19_wblj5bv5wyph7hw5y5b95jc55b/T/SchemeScriptAction-Qjp2Sy: line 2: $: command not found

xcodebuild command I am using
_xcodebuild -IDEBuildLocationStyle=Custom -IDECustomBuildLocationType=Absolute -IDECustomBuildProductsPath="$PWD/build/Products" -scheme 'Staging' -workspace 'lng.xcworkspace' -destination 'platform=iOS Simulator,name=iPhone 5,OS=10.1' build-for-testing_

**Comment by okan-erdogan** [comment]
hi i am able to run my test now thanks.

**Comment by plu** [comment]
Happy to hear that!
